const themesData = [
    {
        search: "CALL ME BY YOUR NAME 日夜 彩色",
        coverImg: "./images/CALL ME/CALL ME首图.jpg",
        date: "Jul 11, 2026",
        title: "CALL ME BY YOUR NAME",
        tags: ["彩色", "日夜"],
        detailImgs: "./images/CALL ME/CALL ME首图.jpg,./images/CALL ME/CALL ME日间.jpg,./images/CALL ME/CALL ME夜间.jpg",
        startup: "有",
        carousel: "无",
        cover: "日间3个，夜间1个",
        homeBg: "1个",
        readBg: "1个",
        highlight: "标题",
        intro: "我做的第一个主题！<br><br>图源网络<br><br>AI和手机美图秀秀的杰作<br><br>现在看还是挺喜欢的<br><br>当时不会调界面颜色，看着有点别扭，我又调了一下重新打包<br><br>大家随便吃吃",
        xhsLink: "https://xhslink.cn/o/4fOEyJcGPTe",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMWhiV044Y2lVX2hYeU55OGN2Z3JtR0E="
    },
    {
        search: "简约唱片 简约 黑白",
        coverImg: "./images/简约唱片/日间.jpg",
        date: "Jul 16, 2026",
        title: "简约唱片",
        tags: ["简约","黑白", "日夜"],
        detailImgs: "./images/简约唱片/日间.jpg,./images/简约唱片/夜间.jpg",
        startup: "有",
        carousel: "4个",
        cover: "5个",
        homeBg: "日间3个，夜间1个",
        readBg: "1个",
        highlight: "标题",
        intro: "基本都是AI生成<br><br>手机美图秀秀拼接<br><br>日间三个阅读背景，纯白色还有灰色护眼的",
        xhsLink: "https://xhslink.cn/o/6mp22y0bxN7",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMVZQdlZ1MW82d005RzQ2R2ZfbjdVaXc="
    },
    {
        search: "维基百科 wiki 黑白 极简 简约 日夜",
        coverImg: "./images/维基百科/日间.jpg",
        date: "Aug 21, 2026",
        title: "维基百科",
        subtitle: "The sum of all human knowledge.",
        tags: ["极简","简约","黑白", "日夜"],
        detailImgs: "./images/维基百科/日间.jpg,./images/维基百科/夜间.jpg",
        startup: "有",
        carousel: "1个",
        cover: "1个",
        homeBg: "1个",
        readBg: "1个",
        highlight: "无",
        intro: "一个黑白极简款<br><br>日夜双版本<br><br>没有任何图片，是我做的最容易的一个主题😭<br><br>非常适合看书！<br><br>The sum of all human knowledge.",
        xhsLink: "https://xhslink.cn/o/AHbEfd4IIEK",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMTF2dVo5OVZZY1pmQ1k2NmxOM2haT2c="
    },
    {
        search: "女性主义 简约 低饱和 舒适 莫兰迪 柔和",
        coverImg: "./images/女性主义/女性主义预览图.jpg",
        date: "Aug 23, 2026",
        title: "女性主义",
        subtitle: "Own your space, embrace your grace.",
        tags: ["简约","低饱和", "莫兰迪", "优雅", "舒适", "柔和"],
        detailImgs: "./images/女性主义/女性主义预览图.jpg,./images/女性主义/预览一版.jpg,./images/女性主义/预览二版.jpg",
        startup: "有",
        carousel: "1个",
        cover: "5个",
        homeBg: "1个",
        readBg: "2个",
        highlight: "标题，对话",
        intro: "一个简约优雅的女性专属主题！<br><br>两个版本的阅读背景，直接在看书页面切换夜间主题就行，主页不会变<br><br>图基本都是我自己做的，女性极简线条画来自pin，侵删<br><br>每天两眼一睁就是做图做图做图😭<br><br>这款颜色非常舒服，低饱和莫兰迪奶茶色系<br><br>看书特别舒适",
        xhsLink: "https://xhslink.cn/o/5FD4woXitby",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMXotUzNNa1ltclpGWVBKSEFJSm5Td2c="
    },
    {
        search: "Timeline 简约 极简 多色 日夜 三色 黑白",
        coverImg: "./images/Timeline/Timeline预览首图.jpg",
        date: "Aug 24, 2026",
        title: "Timeline",
        subtitle: "Reading in the flow of time.",
        tags: ["极简","简约", "三色", "黑白"],
        detailImgs: "./images/Timeline/Timeline预览首图.jpg,./images/Timeline/黑白预览.jpg,./images/Timeline/复古红预览.jpg,./images/Timeline/深海蓝预览.jpg",
        startup: "有",
        carousel: "2个",
        cover: "1个",
        homeBg: "1个",
        readBg: "1个",
        highlight: "对话",
        intro: "一个极简三色主题<br><br>经典黑白，复古红，深海蓝<br><br>每个颜色都有日夜双版",
        xhsLink: "https://xhslink.cn/o/9LziZwLhsOR",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMWJud3ljVmloRzZqYkQzZ0p2WDc3VkE="
    },
    {
        search: "栖阅 简约 中性 舒适 柔和 低饱和 莫兰迪",
        coverImg: "./images/栖阅/预览.png",
        date: "Aug 25, 2026",
        title: "栖阅",
        subtitle: "Read in silence.Dwell in clam.",
        tags: ["简约", "中性", "低饱和", "莫兰迪", "舒适", "柔和"],
        detailImgs: "./images/栖阅/预览.png",
        startup: "有",
        carousel: "1个",
        cover: "4个",
        homeBg: "1个",
        readBg: "2个版本",
        highlight: "对话",
        intro: "一个简约低饱和莫兰迪色系的图片拼贴主题<br><br>这次的色系偏中性<br><br>依然非常舒服<br><br>照例做了两个版本的阅读背景<br><br>因为头版空间小，所以又做了个阅读空间大的版本<br><br>二版绑在夜间模式，直接在阅读页面切换夜间模式即可<br><br>真的很喜欢这种淡淡的感觉呀~",
        xhsLink: "https://xhslink.cn/o/9sOgIbg0ac3",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMVBnSVpaRl9VelRUd0hmOUpnYkZNQVE="
    },
    {
        search: "Kpop 简约 韩系 清透 玻璃 紫色",
        coverImg: "./images/Kpop/紫色首图.jpg",
        date: "Sep 7, 2026",
        title: "Kpop紫",
        subtitle: "어둠이 드리워질 때도 겁내지 마 너무 아름다워서 꽃잎 활짝 펴서",
        tags: ["简约", "韩系", "清透", "玻璃", "紫色", "柔和"],
        detailImgs: "./images/Kpop/紫色首图.jpg,./images/Kpop/紫色1.jpg,./images/Kpop/紫色2.jpg,",
        startup: "有",
        carousel: "2个",
        cover: "9个专辑封面",
        homeBg: "1个",
        readBg: "1个",
        highlight: "对话",
        intro: "一个韩系Kpop主题<br><br>仿的是QQ音乐浅色轻盈彩胶播放器样式<br><br>看到的时候就觉得非常适合做成主题<br><br>但我失败了，好像毁了<br><br>就这样吧<br><br>图片找了很久，都是QQ音乐的专辑封面图<br><br>按照合适的颜色选的图，和个人喜好、排名无关<br><br>大家可以二改自己喜欢的图片<br><br>有小生活紫色版的也可以搭配紫色日历轮播图，非常适配！",
        xhsLink: "https://xhslink.cn/o/9sOgIbg0ac3",
        diskBase64: "aHR0cHM6Ly9wYW4uYmFpZHUuY29tL3MvMWtDRFdLSGo1UFhxTS1teWp6bk1PX3c="
    },
    
];